from __future__ import annotations

import json
import zipfile
from pathlib import Path
from typing import Any


def build_blender_script(job: dict[str, Any]) -> str:
    """Create a standalone Blender Python script from an Oyen animation job."""
    job_json = json.dumps(job, ensure_ascii=False, indent=2)
    template = r'''# Generated by Oyen AI Animation Studio V0.2
# Run with:
# blender --background --factory-startup --enable-autoexec --python oyen_blender_scene.py

from __future__ import annotations

import json
import math
import os
import traceback

import bpy
from mathutils import Vector

JOB = json.loads(r"""__JOB_JSON__""")
OUTPUT_ROOT = os.path.abspath("//oyen_output")
BLEND_PATH = os.path.join(OUTPUT_ROOT, "oyen_preview.blend")
VIDEO_PATH = os.path.join(OUTPUT_ROOT, "oyen_preview.mp4")


def log(message: str) -> None:
    print(f"OYEN_WORKER: {message}")


def clear_scene() -> None:
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for datablocks in (
        bpy.data.meshes,
        bpy.data.curves,
        bpy.data.materials,
        bpy.data.cameras,
        bpy.data.lights,
    ):
        for datablock in list(datablocks):
            if datablock.users == 0:
                datablocks.remove(datablock)


def make_material(name: str, color: tuple[float, float, float, float], roughness: float = 0.6):
    material = bpy.data.materials.new(name=name)
    material.diffuse_color = color
    material.use_nodes = True
    bsdf = material.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        bsdf.inputs["Base Color"].default_value = color
        bsdf.inputs["Roughness"].default_value = roughness
    return material


def add_uv_sphere(name, location, scale, material, parent=None):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=32, ring_count=16, location=location)
    obj = bpy.context.active_object
    obj.name = name
    obj.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.data.materials.append(material)
    if parent is not None:
        obj.parent = parent
    return obj


def add_cone(name, location, scale, material, parent=None):
    bpy.ops.mesh.primitive_cone_add(vertices=24, radius1=1.0, radius2=0.0, depth=2.0, location=location)
    obj = bpy.context.active_object
    obj.name = name
    obj.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.data.materials.append(material)
    if parent is not None:
        obj.parent = parent
    return obj


def add_cylinder(name, location, scale, material, rotation=(0.0, 0.0, 0.0), parent=None):
    bpy.ops.mesh.primitive_cylinder_add(vertices=24, location=location, rotation=rotation)
    obj = bpy.context.active_object
    obj.name = name
    obj.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.data.materials.append(material)
    if parent is not None:
        obj.parent = parent
    return obj


def create_oyen():
    orange = make_material("Oyen Orange", (0.95, 0.28, 0.035, 1.0), 0.72)
    cream = make_material("Oyen Cream", (1.0, 0.72, 0.38, 1.0), 0.68)
    dark = make_material("Oyen Dark", (0.035, 0.025, 0.02, 1.0), 0.45)
    pink = make_material("Oyen Nose", (1.0, 0.22, 0.28, 1.0), 0.5)

    root = bpy.data.objects.new("Oyen_Root", None)
    bpy.context.collection.objects.link(root)

    add_uv_sphere("Oyen_Body", (0.0, 0.0, 1.1), (0.72, 0.46, 0.62), orange, root)
    add_uv_sphere("Oyen_Chest", (0.0, -0.38, 1.13), (0.34, 0.09, 0.4), cream, root)
    head = add_uv_sphere("Oyen_Head", (0.0, -0.04, 1.82), (0.52, 0.45, 0.47), orange, root)

    left_ear = add_cone("Oyen_Ear_L", (-0.28, -0.02, 2.27), (0.19, 0.16, 0.34), orange, root)
    right_ear = add_cone("Oyen_Ear_R", (0.28, -0.02, 2.27), (0.19, 0.16, 0.34), orange, root)
    left_ear.rotation_euler[1] = math.radians(-8)
    right_ear.rotation_euler[1] = math.radians(8)

    for x in (-0.18, 0.18):
        eye = add_uv_sphere(f"Oyen_Eye_{x:+.2f}", (x, -0.43, 1.93), (0.085, 0.035, 0.11), dark, root)
        eye.rotation_euler[0] = math.radians(90)

    add_uv_sphere("Oyen_Muzzle_L", (-0.13, -0.46, 1.72), (0.18, 0.07, 0.13), cream, root)
    add_uv_sphere("Oyen_Muzzle_R", (0.13, -0.46, 1.72), (0.18, 0.07, 0.13), cream, root)
    add_uv_sphere("Oyen_Nose", (0.0, -0.535, 1.78), (0.07, 0.035, 0.05), pink, root)

    for x in (-0.34, 0.34):
        add_cylinder(f"Oyen_Leg_{x:+.2f}", (x, 0.0, 0.48), (0.16, 0.16, 0.48), orange, parent=root)
        add_uv_sphere(f"Oyen_Paw_{x:+.2f}", (x, -0.08, 0.08), (0.22, 0.3, 0.11), cream, root)

    tail = add_cylinder(
        "Oyen_Tail",
        (0.73, 0.18, 1.18),
        (0.12, 0.12, 0.75),
        orange,
        rotation=(0.0, math.radians(58), 0.0),
        parent=root,
    )
    tail.rotation_mode = "XYZ"
    return root, head, tail


def add_environment():
    floor_material = make_material("Floor", (0.13, 0.16, 0.2, 1.0), 0.82)
    bpy.ops.mesh.primitive_plane_add(size=30, location=(3.0, 0.0, -0.03))
    floor = bpy.context.active_object
    floor.name = "Oyen_Floor"
    floor.data.materials.append(floor_material)

    bpy.ops.object.light_add(type="AREA", location=(2.5, -4.0, 6.5))
    key = bpy.context.active_object
    key.name = "Oyen_Key_Light"
    key.data.energy = 1100
    key.data.shape = "DISK"
    key.data.size = 5.0
    key.rotation_euler = (math.radians(25), 0.0, math.radians(28))

    bpy.ops.object.light_add(type="AREA", location=(-3.0, 2.0, 3.8))
    fill = bpy.context.active_object
    fill.name = "Oyen_Fill_Light"
    fill.data.energy = 650
    fill.data.size = 4.0
    fill.rotation_euler = (math.radians(55), 0.0, math.radians(-145))

    bpy.ops.object.light_add(type="SUN", location=(0.0, 0.0, 5.0))
    sun = bpy.context.active_object
    sun.name = "Oyen_Sun"
    sun.data.energy = 1.6
    sun.rotation_euler = (math.radians(32), math.radians(-18), math.radians(25))


def point_camera(camera, target: Vector) -> None:
    direction = target - camera.location
    camera.rotation_euler = direction.to_track_quat("-Z", "Y").to_euler()


def create_camera():
    bpy.ops.object.camera_add(location=(7.0, -10.0, 5.0))
    camera = bpy.context.active_object
    camera.name = "Oyen_Camera"
    camera.data.lens = 48
    bpy.context.scene.camera = camera
    point_camera(camera, Vector((0.0, 0.0, 1.2)))
    return camera


def keyframe_bezier(obj, data_path: str) -> None:
    if obj.animation_data and obj.animation_data.action:
        for fcurve in obj.animation_data.action.fcurves:
            if fcurve.data_path == data_path:
                for point in fcurve.keyframe_points:
                    point.interpolation = "BEZIER"


def animate_oyen(root, head, tail, camera):
    timeline = JOB["timeline"]
    fps = int(timeline["fps"])
    scenes = timeline.get("scenes", [])
    if not scenes:
        scenes = [{"start_seconds": 0, "end_seconds": timeline["duration_seconds"], "camera": "wide establishing shot"}]

    for index, shot in enumerate(scenes):
        start = max(1, int(float(shot["start_seconds"]) * fps) + 1)
        end = max(start + 1, int(float(shot["end_seconds"]) * fps))
        base_x = index * 2.35

        root.location = (base_x, 0.0, 0.0)
        root.rotation_euler = (0.0, 0.0, math.radians(-8 if index % 2 else 5))
        root.keyframe_insert(data_path="location", frame=start)
        root.keyframe_insert(data_path="rotation_euler", frame=start)
        root.location = (base_x + 1.75, 0.12 * (-1 if index % 2 else 1), 0.08 if index % 3 == 1 else 0.0)
        root.rotation_euler = (0.0, 0.0, math.radians(12 if index % 2 else -6))
        root.keyframe_insert(data_path="location", frame=end)
        root.keyframe_insert(data_path="rotation_euler", frame=end)

        middle = (start + end) // 2
        head.rotation_euler = (math.radians(-4), 0.0, math.radians(-10 if index % 2 else 10))
        head.keyframe_insert(data_path="rotation_euler", frame=start)
        head.rotation_euler = (math.radians(7), 0.0, math.radians(13 if index % 2 else -13))
        head.keyframe_insert(data_path="rotation_euler", frame=middle)
        head.rotation_euler = (0.0, 0.0, 0.0)
        head.keyframe_insert(data_path="rotation_euler", frame=end)

        tail.rotation_euler[2] = math.radians(-22)
        tail.keyframe_insert(data_path="rotation_euler", frame=start)
        tail.rotation_euler[2] = math.radians(24)
        tail.keyframe_insert(data_path="rotation_euler", frame=middle)
        tail.rotation_euler[2] = math.radians(-18)
        tail.keyframe_insert(data_path="rotation_euler", frame=end)

        shot_name = str(shot.get("camera", "")).lower()
        target = Vector((base_x + 0.85, 0.0, 1.25))
        if "close" in shot_name:
            camera.location = (base_x + 3.0, -4.8, 2.65)
            camera.data.lens = 62
        elif "medium" in shot_name:
            camera.location = (base_x + 4.8, -7.0, 3.25)
            camera.data.lens = 52
        else:
            camera.location = (base_x + 7.0, -10.2, 4.9)
            camera.data.lens = 45

        point_camera(camera, target)
        camera.keyframe_insert(data_path="location", frame=start)
        camera.keyframe_insert(data_path="rotation_euler", frame=start)
        camera.data.keyframe_insert(data_path="lens", frame=start)
        camera.location.x += 0.8
        camera.location.y += 0.35
        point_camera(camera, Vector((base_x + 1.65, 0.0, 1.2)))
        camera.keyframe_insert(data_path="location", frame=end)
        camera.keyframe_insert(data_path="rotation_euler", frame=end)
        camera.data.keyframe_insert(data_path="lens", frame=end)

    for obj, path in ((root, "location"), (root, "rotation_euler"), (head, "rotation_euler"), (tail, "rotation_euler"), (camera, "location"), (camera, "rotation_euler")):
        keyframe_bezier(obj, path)


def configure_scene():
    scene = bpy.context.scene
    timeline = JOB["timeline"]
    render = JOB["render"]
    scene.frame_start = 1
    scene.frame_end = max(2, int(timeline["total_frames"]))
    scene.render.fps = int(timeline["fps"])
    scene.render.resolution_x = int(render["width"])
    scene.render.resolution_y = int(render["height"])
    scene.render.resolution_percentage = 50
    preferred_engine = str(render.get("engine", "BLENDER_EEVEE_NEXT"))
    available_engines = {"BLENDER_EEVEE_NEXT", "BLENDER_WORKBENCH", "CYCLES"}
    scene.render.engine = preferred_engine if preferred_engine in available_engines else "BLENDER_EEVEE_NEXT"
    scene.render.image_settings.file_format = "FFMPEG"
    scene.render.ffmpeg.format = "MPEG4"
    scene.render.ffmpeg.codec = "H264"
    scene.render.ffmpeg.constant_rate_factor = "MEDIUM"
    scene.render.filepath = VIDEO_PATH
    scene.world.color = (0.025, 0.035, 0.055)


def add_scene_labels():
    for index, shot in enumerate(JOB["timeline"].get("scenes", [])):
        bpy.ops.object.text_add(location=(index * 2.35 + 0.75, 1.15, 0.02), rotation=(0.0, 0.0, 0.0))
        label = bpy.context.active_object
        label.name = f"Oyen_Shot_Label_{index + 1:02d}"
        label.data.body = f"SHOT {index + 1}: {shot.get('action', '')[:42]}"
        label.data.align_x = "CENTER"
        label.data.size = 0.22
        label.data.extrude = 0.005


def main():
    os.makedirs(OUTPUT_ROOT, exist_ok=True)
    log(f"Starting job {JOB.get('job_id', 'unknown')}")
    clear_scene()
    configure_scene()
    add_environment()
    root, head, tail = create_oyen()
    camera = create_camera()
    animate_oyen(root, head, tail, camera)
    add_scene_labels()
    bpy.context.scene.frame_set(1)
    bpy.ops.wm.save_as_mainfile(filepath=BLEND_PATH)
    log(f"Blend saved: {BLEND_PATH}")
    bpy.ops.render.render(animation=True)
    log(f"Video rendered: {VIDEO_PATH}")
    print("OYEN_WORKER_SUCCESS")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"OYEN_WORKER_ERROR: {exc}")
        print(traceback.format_exc())
        raise
'''
    return template.replace("__JOB_JSON__", job_json)


def _run_script_sh() -> str:
    return """#!/usr/bin/env bash
set -euo pipefail
BLENDER_BIN="${BLENDER_EXECUTABLE:-blender}"
"$BLENDER_BIN" --background --factory-startup --enable-autoexec --python oyen_blender_scene.py
"""


def _run_script_bat() -> str:
    return r"""@echo off
setlocal
if "%BLENDER_EXECUTABLE%"=="" (
  set "BLENDER_BIN=blender"
) else (
  set "BLENDER_BIN=%BLENDER_EXECUTABLE%"
)
"%BLENDER_BIN%" --background --factory-startup --enable-autoexec --python oyen_blender_scene.py
if errorlevel 1 exit /b %errorlevel%
echo Oyen render selesai. Periksa folder oyen_output.
"""


def _package_readme(job: dict[str, Any]) -> str:
    return f"""# Oyen Blender Worker Package

Job: `{job.get("job_id", "unknown")}`

Paket ini dibuat oleh Oyen AI Animation Studio V0.2. Script membangun animatic 3D sederhana tanpa aset eksternal, menyimpan `.blend`, lalu merender MP4 memakai Blender headless.

## Cara menjalankan

### Windows

1. Instal Blender 4.x.
2. Ekstrak ZIP ini.
3. Klik `run_blender.bat`.

Bila perintah `blender` belum masuk PATH, set variabel:

```bat
set BLENDER_EXECUTABLE=C:\\Program Files\\Blender Foundation\\Blender 4.3\\blender.exe
run_blender.bat
```

### Linux/macOS

```bash
chmod +x run_blender.sh
./run_blender.sh
```

## Output

```text
oyen_output/
├── oyen_preview.blend
└── oyen_preview.mp4
```

Preview menggunakan 50% resolusi agar uji awal lebih cepat. Karakter saat ini masih placeholder prosedural; model Oyen rigged akan disambungkan pada fase berikutnya.
"""


def write_worker_package(job: dict[str, Any], output_dir: str | Path) -> dict[str, str]:
    """Write JSON, standalone Blender script, launchers and a ZIP bundle."""
    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)
    job_id = str(job.get("job_id", "oyen-job"))
    job_path = destination / f"{job_id}.json"
    script_path = destination / f"{job_id}_blender.py"
    zip_path = destination / f"{job_id}_worker.zip"
    job_text = json.dumps(job, ensure_ascii=False, indent=2)
    script_text = build_blender_script(job)
    job_path.write_text(job_text, encoding="utf-8")
    script_path.write_text(script_text, encoding="utf-8")
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("animation_job.json", job_text)
        archive.writestr("oyen_blender_scene.py", script_text)
        archive.writestr("run_blender.sh", _run_script_sh())
        archive.writestr("run_blender.bat", _run_script_bat())
        archive.writestr("README.md", _package_readme(job))
    return {"json": str(job_path), "script": str(script_path), "zip": str(zip_path)}
